# Generated by Django 3.2.9 on 2023-01-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20221230_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_black_left_lobby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='_white_left_lobby',
            field=models.BooleanField(default=False),
        ),
    ]
