# Generated by Django 3.2.9 on 2023-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20230105_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_is_lobby_closed',
            field=models.BooleanField(default=False),
        ),
    ]
