# Generated by Django 3.2.9 on 2022-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveSmallIntegerField(default=10)),
                ('seconds', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
