# Generated by Django 3.2.9 on 2022-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
