# Generated by Django 3.2.9 on 2022-08-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_state',
            new_name='fen',
        ),
    ]
