# Generated by Django 3.2.9 on 2022-08-16 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_rename_game_state_game_fen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.AddField(
            model_name='game',
            name='player_black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player_white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to=settings.AUTH_USER_MODEL),
        ),
    ]
