# Generated by Django 3.2.9 on 2022-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_moves_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='endgame_cause',
            field=models.TextField(null=True),
        ),
    ]
