# Generated by Django 3.2.9 on 2022-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_endgame_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
