# Generated by Django 3.2.9 on 2022-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_move_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
