# Generated by Django 3.2.9 on 2022-10-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20221011_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timer_black',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='timer_white',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
