# Generated by Django 4.2 on 2023-06-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_freeboardgame'),
        ('users', '0003_remove_userprofile_is_online_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freeboard_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.freeboardgame'),
        ),
    ]
