# Generated by Django 4.2 on 2023-06-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_freeboard_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='freeboard_game',
        ),
    ]
