# Generated by Django 4.2 on 2023-06-14 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_freeboardgame_freeboard_game'),
        ('users', '0005_remove_user_freeboard_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freeboard_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.freeboardgame'),
        ),
    ]
