# Generated by Django 3.2.9 on 2022-12-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_game_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_move_cancel_fen',
            field=models.TextField(default=None, null=True),
        ),
    ]
