# Generated by Django 2.1.5 on 2021-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211109_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank_profile_pic.png', null=True, upload_to=''),
        ),
    ]
