# Generated by Django 2.1.5 on 2021-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211115_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/blank_profile_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
