version: '3.7'

services:
  backend:
    container_name: backend
    build: backend
    ports:
     - "8000:8000"
    volumes:
      - static:/static
      - media:/media
    environment:
      - DEBUG=1

  frontend:
    container_name: frontend
    build: frontend
    ports:
     - "4200:4200"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

volumes:
 static:
 media:
 