# Generated by Django 4.2 on 2023-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('game_positions', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('endgame_cause', models.TextField(null=True)),
                ('_game_result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('timer_black', models.PositiveIntegerField()),
                ('timer_white', models.PositiveIntegerField()),
                ('is_running', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('game_positions', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('move_timestamps', models.TextField()),
                ('endgame_cause', models.TextField(null=True)),
                ('game_start_time', models.DateTimeField(default=None, null=True)),
                ('last_move_time', models.DateTimeField(default=None, null=True)),
                ('game_end_time', models.DateTimeField(default=None, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('random_colors', models.BooleanField()),
                ('_move_cancel_fen', models.TextField(default=None, null=True)),
                ('_game_result', models.TextField(null=True)),
            ],
        ),
    ]
