# Generated by Django 4.2 on 2023-06-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_freeboardgame_freeboard_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeboardgame',
            name='freeboard_game',
        ),
    ]
