# Generated by Django 3.2.9 on 2022-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('timer_black', models.PositiveIntegerField(default=300)),
                ('timer_white', models.PositiveIntegerField(default=300)),
                ('is_running', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('game_positions', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('endgame_cause', models.TextField(null=True)),
                ('game_start_time', models.DateTimeField(default=None, null=True)),
                ('last_move_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
