# Generated by Django 3.2.9 on 2022-11-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='moves_list',
            new_name='game_positions',
        ),
    ]
