# Generated by Django 3.2.9 on 2022-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20221124_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_timestamps',
            field=models.TextField(default='300-300'),
        ),
    ]
