# Generated by Django 3.2.9 on 2022-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_move_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
