# Generated by Django 3.2.9 on 2022-12-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game__move_cancel_fen'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='random_colors',
            field=models.BooleanField(null=True),
        ),
    ]
