# Generated by Django 3.2.9 on 2023-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game__game_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='_black_left_lobby',
        ),
        migrations.RemoveField(
            model_name='game',
            name='_is_lobby_closed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='_white_left_lobby',
        ),
    ]
