# Generated by Django 3.2.9 on 2022-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_history',
            field=models.ManyToManyField(to='game.Game'),
        ),
    ]
